version: "3.7"
services:
  chaingreen-explorer-backend:
    image: docker.pkg.github.com/valerid/chaingreen-explorer-backend/chaingreen-explorer-backend:sha-b40fa0a
    network_mode: "host"
    volumes:
      - /root/.chaingreen:/root/.chaingreen
    environment:

      ## Server's params ##
     
      - HOST=chaingreen-explorer-server  #Server's IP
      
      - PORT=3000 #Server's port
      
      ## FullNode parameters ##
      
      - FULLNODE_PORT=8855 #FullNode port
      
      - FULLNODE_HOST=localhost #FullNode's host address

      # FullNode's certificate and key
      - FULLNODE_CERTPATH=/root/.chaingreen/mainnet/config/ssl/full_node/private_full_node.crt
      - FULLNODE_KEYPATH=/root/.chaingreen/mainnet/config/ssl/full_node/private_full_node.key  
      
      ## Database parameters ##

      - DB_NAME=chaingreen # Database's name
      
      - DB_HOST=localhost # Database's host IP
      
      - DB_PORT=27017 # Database's port
      
  chaingreen-explorer-frontend:
    image: docker.pkg.github.com/valerid/chaingreen-explorer-frontend/chaingreen-explorer-frontend:sha-44a8166
    ports:
      - "5000:80"
